
import { AppEvent, Summary } from "./types";
import { subDays, startOfToday, format, subHours } from "date-fns";

const today = startOfToday();

// テスト用に10枚以上のカードを用意
export const PREVIEW_EVENTS: AppEvent[] = [
  {
    id: "preview-ev-1",
    userId: "preview-user-123",
    googleEventId: "preview-ev-1",
    title: "重要な戦略ミーティング",
    description: "次期プロジェクトの方向性について",
    startAt: new Date(today.getTime() + 10 * 60 * 60 * 1000).toISOString(),
    endAt: new Date(today.getTime() + 11 * 60 * 60 * 1000).toISOString(),
    calendarId: "primary",
    calendarName: "メインカレンダー",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-2",
    userId: "preview-user-123",
    googleEventId: "preview-ev-2",
    title: "読書・インプット時間",
    description: "技術書のキャッチアップ",
    startAt: new Date(today.getTime() + 14 * 60 * 60 * 1000).toISOString(),
    endAt: new Date(today.getTime() + 15 * 60 * 60 * 1000).toISOString(),
    calendarId: "primary",
    calendarName: "メインカレンダー",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-3",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-3",
    title: "クライアントへの返信",
    startAt: subHours(today, 1).toISOString(),
    endAt: today.toISOString(),
    calendarId: "primary",
    calendarName: "仕事",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-4",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-4",
    title: "ランチミーティング",
    startAt: subHours(today, 2).toISOString(),
    endAt: subHours(today, 1).toISOString(),
    calendarId: "primary",
    calendarName: "メインカレンダー",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-5",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-5",
    title: "コードレビュー",
    startAt: subHours(today, 3).toISOString(),
    endAt: subHours(today, 2).toISOString(),
    calendarId: "primary",
    calendarName: "開発",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-6",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-6",
    title: "ジム・トレーニング",
    startAt: subHours(today, 4).toISOString(),
    endAt: subHours(today, 3).toISOString(),
    calendarId: "primary",
    calendarName: "習慣",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-7",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-7",
    title: "定例進捗報告",
    startAt: subHours(today, 5).toISOString(),
    endAt: subHours(today, 4).toISOString(),
    calendarId: "primary",
    calendarName: "仕事",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-8",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-8",
    title: "メールチェック・整理",
    startAt: subHours(today, 6).toISOString(),
    endAt: subHours(today, 5).toISOString(),
    calendarId: "primary",
    calendarName: "仕事",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-9",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-9",
    title: "プロジェクト資料作成",
    startAt: subHours(today, 7).toISOString(),
    endAt: subHours(today, 6).toISOString(),
    calendarId: "primary",
    calendarName: "仕事",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-10",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-10",
    title: "夕食・休憩",
    startAt: subHours(today, 8).toISOString(),
    endAt: subHours(today, 7).toISOString(),
    calendarId: "primary",
    calendarName: "メインカレンダー",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-11",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-11",
    title: "明日への準備",
    startAt: subHours(today, 9).toISOString(),
    endAt: subHours(today, 8).toISOString(),
    calendarId: "primary",
    calendarName: "習慣",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-test-12",
    userId: "preview-user-123",
    googleEventId: "preview-ev-test-12",
    title: "深夜の静寂時間",
    startAt: subHours(today, 10).toISOString(),
    endAt: subHours(today, 9).toISOString(),
    calendarId: "primary",
    calendarName: "習慣",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: false,
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "preview-ev-3",
    userId: "preview-user-123",
    googleEventId: "preview-ev-3",
    title: "昨日のタスク振り返り",
    description: "完了したタスクの整理",
    startAt: subDays(today, 1).toISOString(),
    endAt: subDays(today, 1).toISOString(),
    calendarId: "primary",
    calendarName: "メインカレンダー",
    syncStatus: "synced",
    source: "google_calendar",
    isReported: true,
    reportStatus: "done",
    reportMemo: "集中して取り組めた。",
    lastSyncedAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }
];

export const PREVIEW_SUMMARIES: Summary[] = [
  {
    id: `daily-${format(today, "yyyy-MM-dd")}`,
    userId: "preview-user-123",
    summaryType: "daily",
    startDate: format(today, "yyyy-MM-dd"),
    endDate: format(today, "yyyy-MM-dd"),
    summaryText: "今日は朝から集中力が高い。午後のルーチンも守れた。",
    updatedAt: Date.now(),
  }
];
